replicaCount: 2

image:
  repository: ghcr.io/merajansari87/githubactions-helm-argocd
  tag: "ff32aec1b13b677b42c058735230ebade9f16ea2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 80
